### ISSUE TITLE
To-do: Intro to git and midway2

### ISSUE THREAD

**Issue by linghui-wu** [energy-policy-institute-uchicago/RP-orientation-2022#2]
- [x] Update intro to git slides with windows shell and GUI
- [x] Midway2 cannot be connected now and commit `sbatch` scripts when it comes back to life
- [x] Add `ReadMe` documentation for intro to git and midway2
